controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login_check:
    path: /api/login_check

app_register:
    path: /api/registration
    controller: 'App\Controller\RegistrationController::registration'
    methods: ['POST']